### ISSUE TITLE
make clean: add rnnlm.o

### ISSUE THREAD

**Issue by akoehn** [yandex/faster-rnnlm#12]
This is too trivial for a pull request: 

Currently, the "clean" target only deletes rnnlm and $(OBJ_FILES). However, rnnlm.o is not contained in OBJ_FILES.

Therefore, it would be great to add rnnlm.o:
```
clean:
    rm -f rnnlm rnnlm.o $(OBJ_FILES)
```

Thanks for providing faster-rnnlm!

**Comment by akhti** [comment]
Fixed. Thanks!
