### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [yandex/faster-rnnlm#8]
Would you like to add more error handling for return values from functions like the following?
- [fread](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fread.html "binary input") ⇒ [ReadHeader](https://github.com/yandex/faster-rnnlm/blob/ce038058488a17a34e069e23f71aa5b61e0fc3bf/faster-rnnlm/nnet.cc#L19)
- [fseek](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html "reposition a file-position indicator") ⇒ [WordReader constructor](https://github.com/yandex/faster-rnnlm/blob/5707ecf1d5ab014741a84d92692ce873b8d5e900/faster-rnnlm/words.cc#L27)

**Comment by akhti** [comment]
Yeap, this should be done.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by elfring** [comment]
* Are there [a few update candidates](https://github.com/yandex/faster-rnnlm/blob/038a4ebee0e14f16e3d61e06a470f9e02b080c7a/faster-rnnlm/rnnlm.cc#L417 "Checking pthread_create() in TrainLM()?") left over?
* How do you think about to annotate any functions with "[`__attribute__((warn_unused_result))`](https://gcc.gnu.org/onlinedocs/gcc-5.2.0/gcc/Function-Attributes.html#index-g_t_0040code_007bwarn_005funused_005fresult_007d-function-attribute-3299 "Warn on unused results?")"?
